// BuildKart pilot catalog — construction / hardware marketplace products.
// Titles, brands and colorways are invented for a trademark-safe demo; they do not
// reference any real brand or protected product design. Prices are INR and
// market-realistic for the Indian construction-supply category.

export type SeedCatalogItem = {
  title: string;
  brand: string;
  colorway: string;
  category:
    | "Construction"
    | "Bathroom & Plumbing"
    | "Tiles & Plywood"
    | "Electrical"
    | "Agriculture & Seeds"
    | "Pumps & Machines";
  price: number;
  description: string;
};

export const seedCatalog: SeedCatalogItem[] = [
  // ── Construction ────────────────────────────────────────────────
  {
    title: "Powerex Cordless Drill Driver 18V",
    brand: "Powerex",
    colorway: "Black",
    category: "Construction",
    price: 8499,
    description: "18V cordless drill driver with 2-speed gearbox and 21 torque settings.",
  },
  {
    title: "Powerex Angle Grinder 4-Inch 850W",
    brand: "Powerex",
    colorway: "Green",
    category: "Construction",
    price: 2899,
    description: "850W 4-inch angle grinder with spindle lock and side handle.",
  },
  {
    title: "Powerex Impact Drill 13mm 710W",
    brand: "Powerex",
    colorway: "Grey",
    category: "Construction",
    price: 3499,
    description: "710W 13mm impact drill for concrete and masonry with hammer mode.",
  },
  {
    title: "Powerex Rotary Hammer 26mm 800W",
    brand: "Powerex",
    colorway: "Blue",
    category: "Construction",
    price: 12999,
    description: "26mm SDS-plus rotary hammer for heavy drilling and chiselling.",
  },
  {
    title: "Powerex Circular Saw 7-Inch 1400W",
    brand: "Powerex",
    colorway: "Red",
    category: "Construction",
    price: 6799,
    description: "1400W 7-inch circular saw with laser guide and 45-degree bevel.",
  },
  {
    title: "Powerex Jigsaw 650W",
    brand: "Powerex",
    colorway: "Orange",
    category: "Construction",
    price: 4299,
    description: "650W jigsaw with variable speed and orbital action for curved cuts.",
  },
  {
    title: "BuildPro Hand Tool Kit 120-Piece",
    brand: "BuildPro",
    colorway: "Black",
    category: "Construction",
    price: 3999,
    description: "120-piece hand tool kit in a hard case for general site work.",
  },
  {
    title: "BuildPro Screwdriver Set 24-Piece",
    brand: "BuildPro",
    colorway: "Multicolor",
    category: "Construction",
    price: 799,
    description: "24-piece insulated screwdriver set with ergonomic handles.",
  },
  {
    title: "BuildPro Industrial Safety Helmet",
    brand: "BuildPro",
    colorway: "Yellow",
    category: "Construction",
    price: 449,
    description: "ISI-marked industrial safety helmet with adjustable ratchet.",
  },

  // ── Bathroom & Plumbing ─────────────────────────────────────────
  {
    title: "AquaTek Basin Mixer Tap",
    brand: "AquaTek",
    colorway: "Grey",
    category: "Bathroom & Plumbing",
    price: 2499,
    description: "Chrome-finish basin mixer tap with ceramic disc cartridge.",
  },
  {
    title: "AquaTek Rainfall Shower Head",
    brand: "AquaTek",
    colorway: "Grey",
    category: "Bathroom & Plumbing",
    price: 1899,
    description: "200mm rainfall shower head with self-cleaning nozzles.",
  },
  {
    title: "AquaTek Wall-Mount Faucet",
    brand: "AquaTek",
    colorway: "Grey",
    category: "Bathroom & Plumbing",
    price: 1299,
    description: "Wall-mount faucet with quarter-turn ceramic valve.",
  },
  {
    title: "AquaTek Ceramic Wash Basin",
    brand: "AquaTek",
    colorway: "White",
    category: "Bathroom & Plumbing",
    price: 3499,
    description: "Glazed ceramic wash basin with overflow and 560mm width.",
  },
  {
    title: "AquaTek Western Toilet Commode",
    brand: "AquaTek",
    colorway: "White",
    category: "Bathroom & Plumbing",
    price: 8999,
    description: "Floor-mount western commode with dual-flush cistern.",
  },
  {
    title: "AquaTek PVC Pipe 4-Inch 3m",
    brand: "AquaTek",
    colorway: "White",
    category: "Bathroom & Plumbing",
    price: 649,
    description: "4-inch PVC drainage pipe, 3-metre length, schedule 40.",
  },
  {
    title: "AquaTek PPR Pipe 25mm 3m",
    brand: "AquaTek",
    colorway: "Green",
    category: "Bathroom & Plumbing",
    price: 429,
    description: "25mm PPR hot/cold water pipe, 3-metre length, PN16.",
  },

  // ── Tiles & Plywood ─────────────────────────────────────────────
  {
    title: "TileCraft Vitrified Floor Tile 60x60",
    brand: "TileCraft",
    colorway: "Grey",
    category: "Tiles & Plywood",
    price: 1099,
    description: "60x60cm double-charge vitrified floor tile, box of 4.",
  },
  {
    title: "TileCraft Wall Tile 30x45",
    brand: "TileCraft",
    colorway: "Beige",
    category: "Tiles & Plywood",
    price: 899,
    description: "30x45cm glazed wall tile, box of 6.",
  },
  {
    title: "TileCraft Anti-Skid Floor Tile 30x30",
    brand: "TileCraft",
    colorway: "Brown",
    category: "Tiles & Plywood",
    price: 749,
    description: "30x30cm anti-skid floor tile for wet areas, box of 8.",
  },
  {
    title: "WoodWise Plywood Sheet 18mm 8x4",
    brand: "WoodWise",
    colorway: "Brown",
    category: "Tiles & Plywood",
    price: 3299,
    description: "18mm BWR-grade plywood sheet, 8x4 feet.",
  },
  {
    title: "WoodWise Blockboard 19mm 8x4",
    brand: "WoodWise",
    colorway: "Brown",
    category: "Tiles & Plywood",
    price: 2799,
    description: "19mm hardwood blockboard sheet, 8x4 feet.",
  },
  {
    title: "WoodWise Laminboard 18mm 8x4",
    brand: "WoodWise",
    colorway: "Brown",
    category: "Tiles & Plywood",
    price: 2499,
    description: "18mm laminated MDF board, 8x4 feet, both sides laminated.",
  },
  {
    title: "TileCraft Tile Adhesive 20kg",
    brand: "TileCraft",
    colorway: "Grey",
    category: "Tiles & Plywood",
    price: 549,
    description: "20kg polymer-modified tile adhesive for floor and wall.",
  },

  // ── Electrical ──────────────────────────────────────────────────
  {
    title: "VoltEdge Copper Wire 1.5sqmm 90m",
    brand: "VoltEdge",
    colorway: "Red",
    category: "Electrical",
    price: 2199,
    description: "1.5sqmm single-core copper wire, 90-metre coil.",
  },
  {
    title: "VoltEdge Copper Wire 2.5sqmm 90m",
    brand: "VoltEdge",
    colorway: "Blue",
    category: "Electrical",
    price: 3599,
    description: "2.5sqmm single-core copper wire, 90-metre coil.",
  },
  {
    title: "VoltEdge LED Panel Light 22W",
    brand: "VoltEdge",
    colorway: "White",
    category: "Electrical",
    price: 699,
    description: "22W LED panel light, 6000K, for false ceilings.",
  },
  {
    title: "VoltEdge LED Bulb 9W 4-Pack",
    brand: "VoltEdge",
    colorway: "White",
    category: "Electrical",
    price: 399,
    description: "9W LED bulb, 6500K, pack of 4.",
  },
  {
    title: "VoltEdge Modular Switch 1-Way",
    brand: "VoltEdge",
    colorway: "White",
    category: "Electrical",
    price: 149,
    description: "16A one-way modular switch with silver contacts.",
  },
  {
    title: "VoltEdge Modular Socket 16A",
    brand: "VoltEdge",
    colorway: "White",
    category: "Electrical",
    price: 249,
    description: "16A modular socket with shutter and back-box.",
  },
  {
    title: "VoltEdge MCB 32A 4-Pack",
    brand: "VoltEdge",
    colorway: "Grey",
    category: "Electrical",
    price: 599,
    description: "32A single-pole MCB, pack of 4, C-curve.",
  },
  {
    title: "VoltEdge Extension Cord 4-Way 3m",
    brand: "VoltEdge",
    colorway: "Black",
    category: "Electrical",
    price: 799,
    description: "4-way extension cord, 3-metre, with surge protection.",
  },

  // ── Agriculture & Seeds ─────────────────────────────────────────
  {
    title: "AgriGrow Hybrid Tomato Seeds 100g",
    brand: "AgriGrow",
    colorway: "Red",
    category: "Agriculture & Seeds",
    price: 249,
    description: "High-yield hybrid tomato seeds, 100g pack.",
  },
  {
    title: "AgriGrow Hybrid Chilli Seeds 50g",
    brand: "AgriGrow",
    colorway: "Red",
    category: "Agriculture & Seeds",
    price: 199,
    description: "Hybrid chilli seeds with high pungency, 50g pack.",
  },
  {
    title: "AgriGrow NPK Fertilizer 20:20:20 1kg",
    brand: "AgriGrow",
    colorway: "Green",
    category: "Agriculture & Seeds",
    price: 299,
    description: "Water-soluble NPK 20:20:20 fertilizer, 1kg.",
  },
  {
    title: "AgriGrow Organic Vermicompost 5kg",
    brand: "AgriGrow",
    colorway: "Brown",
    category: "Agriculture & Seeds",
    price: 449,
    description: "Organic vermicompost for soil enrichment, 5kg bag.",
  },
  {
    title: "AgriGrow Garden Hand Trowel",
    brand: "AgriGrow",
    colorway: "Green",
    category: "Agriculture & Seeds",
    price: 199,
    description: "Stainless-steel garden hand trowel with wooden handle.",
  },
  {
    title: "AgriGrow Garden Secateurs",
    brand: "AgriGrow",
    colorway: "Green",
    category: "Agriculture & Seeds",
    price: 499,
    description: "Bypass garden secateurs for pruning and cutting.",
  },
  {
    title: "AgriGrow Spray Pump 2L",
    brand: "AgriGrow",
    colorway: "Green",
    category: "Agriculture & Seeds",
    price: 349,
    description: "2-litre manual spray pump for garden and pest control.",
  },

  // ── Pumps & Machines ────────────────────────────────────────────
  {
    title: "Machina Submersible Pump 1HP",
    brand: "Machina",
    colorway: "Blue",
    category: "Pumps & Machines",
    price: 7499,
    description: "1HP submersible pump for borewells up to 150 feet.",
  },
  {
    title: "Machina Centrifugal Pump 0.5HP",
    brand: "Machina",
    colorway: "Blue",
    category: "Pumps & Machines",
    price: 3999,
    description: "0.5HP self-priming centrifugal pump for domestic water.",
  },
  {
    title: "Machina Booster Pump 0.5HP",
    brand: "Machina",
    colorway: "Grey",
    category: "Pumps & Machines",
    price: 4499,
    description: "0.5HP pressure booster pump with auto on/off.",
  },
  {
    title: "Machina Diesel Generator 5kVA",
    brand: "Machina",
    colorway: "Green",
    category: "Pumps & Machines",
    price: 58999,
    description: "5kVA diesel generator with electric start.",
  },
  {
    title: "Machina Portable Generator 2kVA",
    brand: "Machina",
    colorway: "Red",
    category: "Pumps & Machines",
    price: 24999,
    description: "2kVA portable petrol generator for small sites.",
  },
  {
    title: "Machina Concrete Mixer 5cu.ft",
    brand: "Machina",
    colorway: "Orange",
    category: "Pumps & Machines",
    price: 32999,
    description: "5 cubic-foot concrete mixer with 1HP motor.",
  },
  {
    title: "Machina Air Compressor 50L",
    brand: "Machina",
    colorway: "Blue",
    category: "Pumps & Machines",
    price: 18499,
    description: "50-litre belt-driven air compressor, 3HP.",
  },
  {
    title: "Machina Welding Machine 200A",
    brand: "Machina",
    colorway: "Red",
    category: "Pumps & Machines",
    price: 9999,
    description: "200A IGBT inverter welding machine, single phase.",
  },
  {
    title: "Machina Bench Drill Press",
    brand: "Machina",
    colorway: "Grey",
    category: "Pumps & Machines",
    price: 14999,
    description: "16mm bench drill press with 5-speed belt drive.",
  },
  {
    title: "Machina Bench Grinder 8-Inch",
    brand: "Machina",
    colorway: "Grey",
    category: "Pumps & Machines",
    price: 5499,
    description: "8-inch bench grinder, 350W, with tool rests.",
  },
  {
    title: "Machina Monoblock Pump 1HP",
    brand: "Machina",
    colorway: "Blue",
    category: "Pumps & Machines",
    price: 6499,
    description: "1HP monoblock water pump for domestic and farm use.",
  },
  {
    title: "Machina High-Pressure Washer",
    brand: "Machina",
    colorway: "Green",
    category: "Pumps & Machines",
    price: 11999,
    description: "1400W high-pressure washer with 130-bar output.",
  },
  {
    title: "Machina Angle Polisher 7-Inch",
    brand: "Machina",
    colorway: "Black",
    category: "Pumps & Machines",
    price: 3799,
    description: "7-inch angle polisher, 1200W, for stone and metal.",
  },
  {
    title: "Machina Water Pressure Pump 1HP",
    brand: "Machina",
    colorway: "Blue",
    category: "Pumps & Machines",
    price: 7999,
    description: "1HP water pressure pump for multi-storey buildings.",
  },
];
